# Generated by Django 4.1.7 on 2023-05-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentsFiltere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FilteringLevel",
                    models.CharField(
                        choices=[
                            ("students", "students"),
                            ("teachers", "teachers"),
                            ("parents", "parents"),
                            ("admins", "admins"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "StudentSpecilized",
                    models.CharField(
                        choices=[
                            ("Web Dev", "Web Dev"),
                            ("Mobile Dev", "Mobile Dev"),
                            ("Game Dev", "Game Dev"),
                            ("security", "security"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "StudentLevel",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "StudentClass",
                    models.CharField(
                        choices=[
                            ("Class 1", "Class 1"),
                            ("Class 2", "Class 2"),
                            ("Class 3", "Class 3"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
