# Generated by Django 4.1.7 on 2023-05-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentsFiltere",
            new_name="StudentsFilter",
        ),
    ]
